flows:
  - type: playground
    id: master_search
    meta:
      order: 0
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Master Search
    config:
      $ref:  "./LAMF/master_search.yaml"
  # - type: playground
  #   id: lamf_credit_line_with_mfc_offline_journey
  #   meta:
  #     order: 1
  #   usecase: LOAN AGAINST MUTUAL FUNDS
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #   description: LAMF Credit Line with Offline Journey
  #   config:
  #     $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_single_redirection
    meta:
      order: 2
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - Mandatory
      - REPORTABLE
    description: LAMF Credit Line with MFC
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_credit_line_with_mfc_single_redirection_with_igm_1.0.0
    meta:
      order: 3
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - Mandatory
      # - REPORTABLE
    description: LAMF Credit Line with MFC With IGM 1.0.0
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_single_redirection._with_igm_1.0.0.yaml"    

  - type: playground
    id: lamf_credit_line_drawdown_with_mfc_single_redirection
    meta:
      order: 4
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "Drawdown - LAMF Credit Line with MFC"
    config:
      $ref:  "./LAMF/lamf_credit_line_drawdown_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_credit_line_prepart_with_mfc_single_redirection
    meta:
      order: 5
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "Pre-Part Payment - LAMF Credit Line with MFC"
    config:
      $ref:  "./LAMF/lamf_credit_line_prepart_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_credit_line_foreclosure_with_mfc_single_redirection
    meta:
      order: 6
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "Foreclosure - LAMF Credit Line with MFC"
    config:
      $ref:  "./LAMF/lamf_credit_line_foreclosure_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_term_loan_with_mfc_single_redirection
    meta:
      order: 7
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "LAMF Term Loan with MFC"
    config:
      $ref:  "./LAMF/lamf_term_loan_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_term_loan_foreclosure_with_mfc_single_redirection
    meta:
      order: 8
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "Foreclosure - LAMF Term Loan with MFC"
    config:
      $ref:  "./LAMF/lamf_term_loan_foreclosure_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_term_loan_prepart_with_mfc_single_redirection
    meta:
      order: 9
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "Pre-Part Payment - LAMF Term Loan with MFC"
    config:
      $ref:  "./LAMF/lamf_term_loan_prepart_with_mfc_single_redirection.yaml"

  - type: playground
    id: lamf_term_loan_missed_emi_with_mfc_single_redirection
    meta:
      order: 10
    usecase: LOAN AGAINST MUTUAL FUNDS
    tags:
      - WORKBENCH
      - REPORTABLE
    description: "Missed EMI - LAMF Term Loan with MFC"
    config:
      $ref:  "./LAMF/lamf_term_loan_missed_emi_with_mfc_single_redirection.yaml"
  # - type: playground
  #   id: lamf_credit_line_with_mfc
  #   meta:
  #     order: 3
  #   usecase: LOAN AGAINST MUTUAL FUNDS
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #   description: LAMF Credit Line with MFC
  #   config:
  #     $ref:  "./LAMF/lamf_credit_line_with_mfc.yaml"        
 
  # - type: playground
  #   id: lamf_credit_line_with_mfc_offline_journey_drawdown
  #   meta:
  #     order: 4
  #   usecase: LOAN AGAINST MUTUAL FUNDS
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #   description: Drawdown - LAMF Credit Line with Offline Journey
  #   config:
  #     $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown.yaml"
  # - type: playground
  #   id: lamf_credit_line_with_mfc_offline_journey_drawdown_foreclosure
  #   meta:
  #     order: 5
  #   usecase: LOAN AGAINST MUTUAL FUNDS
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #   description: Drawdown - LAMF Credit Line with Offline Journey(ForeClosure)
  #   config:
  #     $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown_foreclosure.yaml"
  # - type: playground
  #   id: lamf_credit_line_with_mfc_offline_journey_drawdown_missed_emi
  #   meta:
  #     order: 6
  #   usecase: LOAN AGAINST MUTUAL FUNDS
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #   description: Drawdown - LAMF Credit Line with Offline Journey(Missed EMI)
  #   config:
  #     $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown_missed_emi.yaml"
  # - type: playground
  #   id: lamf_credit_line_with_mfc_offline_journey_drawdown_pre_part
  #   meta:
  #     order: 7
  #   usecase: LOAN AGAINST MUTUAL FUNDS
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #   description: Drawdown - LAMF Credit Line with Offline Journey(Pre Part)
  #   config:
  #     $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown_pre_part.yaml"    


